services:
  # Main service for one-time execution
  xserver-auto-renew:
    build: .
    container_name: xserver-auto-renew
    environment:
      - ID_VPS=${ID_VPS}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    # Run once and exit
    command: ["pnpm", "start"]
    restart: "no"

  # Service for scheduled runs with cron
  xserver-auto-renew-scheduler:
    build: .
    container_name: xserver-auto-renew-scheduler
    environment:
      - ID_VPS=${ID_VPS}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    # Install and run cron
    command: >
      sh -c "
        apk add --no-cache dcron &&
        echo '0 9 * * * cd /app && pnpm start' > /tmp/crontab &&
        crontab /tmp/crontab &&
        crond -f -l 2
      "
    profiles:
      - scheduler
    restart: unless-stopped